spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      enabled: true
      httpclient:
        ssl:
          useInsecureTrustManager: true
    discovery:
      locator:
        enabled: true
    routes:
      - id: httpbin-api
        uri: https://httpbin.org
        predicates:
          - Path=/api/**
        filters:
          - StripPrefix=1

server:
  port: 8080
